### ISSUE TITLE
slower than  skimage.measure.compare_ssim

### ISSUE THREAD

**Issue by WenmuZhou** [VainF/pytorch-msssim#1]
I see this implamentation is slower than `skimage.measure.compare_ssim` in `Tests`

**Comment by VainF** [comment]
Hi

The speed of ssim depends on the optimizations of pytorch (conv). In forward pass, pytorch has additional costs such as building a computational graph.

 This repo aims to improve the performance of blur operations. 2D Conv is not very efficient due to the memory layout (jorge's repo in reference is a very clear implementation but not efficient enough for training on gou)
