### ISSUE TITLE
More faster and less vram occupancy in _ssim function

### ISSUE THREAD

**Issue by One-sixth** [VainF/pytorch-msssim#5]
In my test.

It looks a bit counterintuitive. However, separate operations are indeed more efficient than combining operations.

Use [https://github.com/VainF/pytorch-msssim/issues/3](https://github.com/VainF/pytorch-msssim/issues/3) test code.

replace
```
    mu1, mu2, sigma1_sq, sigma2_sq, sigma12 = (
        concat_out[:, idx*channel:(idx+1)*channel, :, :] for idx in range(5))
```
to
```
    mu1, mu2, sigma1_sq, sigma2_sq, sigma12 = torch.chunk(concat_out, 5, 1)
```
can reduce the running time from 51s to 37s.

replace
```
    concat_input = torch.cat([X, Y, X*X, Y*Y, X*Y], dim=1)
    concat_win = win.repeat(5, 1, 1, 1).to(X.device, dtype=X.dtype)
    concat_out = gaussian_filter(concat_input, concat_win)
    
    mu1, mu2, sigma1_sq, sigma2_sq, sigma12 = (
        concat_out[:, idx*channel:(idx+1)*channel, :, :] for idx in range(5))
```
to
```
    win = win.to(X.device, dtype=X.dtype)
    mu1 = gaussian_filter(X, win)
    mu2 = gaussian_filter(Y, win)
    sigma1_sq = gaussian_filter(X * X, win)
    sigma2_sq = gaussian_filter(Y * Y, win)
    sigma12 = gaussian_filter(X * Y, win)
```
can reduce the running time from 51s to 36s and reduce vram occupancy from 1G to 733MB.

**Comment by VainF** [comment]
Thanks!
I tested it on one TITAN Xp. When batch size is small, chunk is the fastest operation. But I prefer the separate implementations because of its readability.

## Batch Size=20
ori: 23.308195
chunk: 18.668331
separate: 18.056049

## Batch Size=10
ori: 9.595843
chunk: 6.377688
separate: 7.508305

## Batch Size=1
ori: 2.271297
chunk: 1.576237
separate: 1.717758
